<a href="https://colab.research.google.com/github/dakshigoel22/BIG_DATA_606/blob/main/605_hw4_dakshigoel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. What is Neo4j?

**○ Explain what kind of datastore it is, and when it is most useful.**

Neo4j is a native property graph database which means nodes represent entities, relations represents connections and properties represent key-value data stored.

It is most useful when the data is highly connected and the relations matter.

Common use cases include :
1. Recommendation systems
2. Fraud detection
3. Social Networks


**What does Neo4j do natively and why does the idea of “native” matter?**

Native here means that Neo4j is built from the ground up for graphs and not layered on top of another model.

Neo4j natively supports:
1. Graph storage
2. Graph traversal
3. Graph query language
4. Index-free adjacency

Native matters because the relations are physically stored and directly linked . It also makes traversals fast and predictable. Query complexity depends on graph shape, not dataset size

#2. Install and Set Up Neo4J

In [ ]:
! curl -fsSL https://debian.neo4j.com/neotechnology.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/neo4j.gpg
! echo "deb [signed-by=/usr/share/keyrings/neo4j.gpg] https://debian.neo4j.com stable latest"| sudo tee -a /etc/apt/sources.list.d/neo4j.list

deb [signed-by=/usr/share/keyrings/neo4j.gpg] https://debian.neo4j.com stable latest

In [ ]:
! sudo apt-get update

Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:5 https://debian.neo4j.com stable InRelease [44.3 kB]
Get:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:11 https://debian.neo4j.com stable/latest amd64 Packages [8,005 B]
Get:12 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,980 kB]
Get:13 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,960 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,310 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,219 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,844 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,622 kB]
Fetched 24.4 MB in 6s (3,916 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

In [ ]:
! sudo apt-get install neo4j

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  at-spi2-core cypher-shell daemon fonts-dejavu-core fonts-dejavu-extra
  gsettings-desktop-schemas libatk-bridge2.0-0 libatk-wrapper-java
  libatk-wrapper-java-jni libatk1.0-0 libatk1.0-data libatspi2.0-0 libgtk-3-0
  libgtk-3-bin libgtk-3-common librsvg2-common libxcomposite1 libxtst6
  libxxf86dga1 openjdk-21-jre openjdk-21-jre-headless session-migration
  x11-utils
Suggested packages:
  gvfs libnss-mdns fonts-ipafont-gothic fonts-ipafont-mincho
  fonts-wqy-microhei | fonts-wqy-zenhei fonts-indic mesa-utils
The following NEW packages will be installed:
  at-spi2-core cypher-shell daemon fonts-dejavu-core fonts-dejavu-extra
  gsettings-desktop-schemas libatk-bridge2.0-0 libatk-wrapper-java
  libatk-wrapper-java-jni libatk1.0-0 libatk1.0-data libatspi2.0-0 libgtk-3-0
  libgtk-3-bin libgtk-3-common librsvg2-common libxcomposite1 libxtst6
  libxxf86dga1 neo4j openjdk-21-jre openjdk-21-jre-headless session-migration
  x11-utils
0 upgraded, 24 newly installed, 0 to remove and 8 not upgraded.
Need to get 327 MB of archives.
After this operation, 534 MB of additional disk space will be used.
Get:1 https://debian.neo4j.com stable/latest amd64 cypher-shell all 1:2026.03.1 [39.3 MB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 daemon amd64 0.8-1 [60.9 kB]
Get:3 https://debian.neo4j.com stable/latest amd64 neo4j all 1:2026.03.1 [233 MB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 openjdk-21-jre-headless amd64 21.0.10+7-1~22.04 [46.9 MB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-common all 3.24.33-1ubuntu2.2 [239 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-0 amd64 3.24.33-1ubuntu2.2 [3,053 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 openjdk-21-jre amd64 21.0.10+7-1~22.04 [238 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-core all 2.37-2build1 [1,041 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-extra all 2.37-2build1 [2,041 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxxf86dga1 amd64 2:1.1.5-0ubuntu3 [12.6 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy/main amd64 x11-utils amd64 7.7+5build2 [206 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-wrapper-java all 0.38.0-5build1 [53.1 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-wrapper-java-jni amd64 0.38.0-5build1 [49.0 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-bin amd64 3.24.33-1ubuntu2.2 [69.6 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 librsvg2-common amd64 2.52.5+dfsg-3ubuntu0.2 [17.7 kB]
Fetched 327 MB in 4s (74.9 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 24.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package daemon.
(Reading database ... 118194 files and directories currently installed.)
Preparing to unpack .../00-daemon_0.8-1_amd64.deb ...
Unpacking daemon (0.8-1) ...
Selecting previously unselected package openjdk-21-jre-headless:amd64.
Preparing to unpack .../01-openjdk-21-jre-headless_21.0.10+7-1~22.04_amd64.deb ...
Unpacking openjdk-21-jre-headless:amd64 (21.0.10+7-1~22.04) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../02-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../03-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatspi2.0-0:amd64.
Preparing to unpack .../04-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../05-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../06-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package libgtk-3-common.
Preparing to unpack .../07-libgtk-3-common_3.24.33-1ubuntu2.2_all.deb ...
Unpacking libgtk-3-common (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package libgtk-3-0:amd64.
Preparing to unpack .../08-libgtk-3-0_3.24.33-1ubuntu2.2_amd64.deb ...
Unpacking libgtk-3-0:amd64 (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../09-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package openjdk-21-jre:amd64.
Preparing to unpack .../10-openjdk-21-jre_21.0.10+7-1~22.04_amd64.deb ...
Unpacking openjdk-21-jre:amd64 (21.0.10+7-1~22.04) ...
Selecting previously unselected package cypher-shell.
Preparing to unpack .../11-cypher-shell_1%3a2026.03.1_all.deb ...
Unpacking cypher-shell (1:2026.03.1) ...
Selecting previously unselected package neo4j.
Preparing to unpack .../12-neo4j_1%3a2026.03.1_all.deb ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Unpacking neo4j (1:2026.03.1) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../13-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../14-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../15-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Selecting previously unselected package fonts-dejavu-core.
Preparing to unpack .../16-fonts-dejavu-core_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-core (2.37-2build1) ...
Selecting previously unselected package fonts-dejavu-extra.
Preparing to unpack .../17-fonts-dejavu-extra_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-extra (2.37-2build1) ...
Selecting previously unselected package libxxf86dga1:amd64.
Preparing to unpack .../18-libxxf86dga1_2%3a1.1.5-0ubuntu3_amd64.deb ...
Unpacking libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Selecting previously unselected package x11-utils.
Preparing to unpack .../19-x11-utils_7.7+5build2_amd64.deb ...
Unpacking x11-utils (7.7+5build2) ...
Selecting previously unselected package libatk-wrapper-java.
Preparing to unpack .../20-libatk-wrapper-java_0.38.0-5build1_all.deb ...
Unpacking libatk-wrapper-java (0.38.0-5build1) ...
Selecting previously unselected package libatk-wrapper-java-jni:amd64.
Preparing to unpack .../21-libatk-wrapper-java-jni_0.38.0-5build1_amd64.deb ...
Unpacking libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Selecting previously unselected package libgtk-3-bin.
Preparing to unpack .../22-libgtk-3-bin_3.24.33-1ubuntu2.2_amd64.deb ...
Unpacking libgtk-3-bin (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package librsvg2-common:amd64.
Preparing to unpack .../23-librsvg2-common_2.52.5+dfsg-3ubuntu0.2_amd64.deb ...
Unpacking librsvg2-common:amd64 (2.52.5+dfsg-3ubuntu0.2) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up openjdk-21-jre-headless:amd64 (21.0.10+7-1~22.04) ...
update-alternatives: using /usr/lib/jvm/java-21-openjdk-amd64/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-21-openjdk-amd64/bin/jpackage to provide /usr/bin/jpackage (jpackage) in auto mode
update-alternatives: using /usr/lib/jvm/java-21-openjdk-amd64/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
update-alternatives: using /usr/lib/jvm/java-21-openjdk-amd64/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode
update-alternatives: using /usr/lib/jvm/java-21-openjdk-amd64/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up fonts-dejavu-core (2.37-2build1) ...
Setting up daemon (0.8-1) ...
Setting up librsvg2-common:amd64 (2.52.5+dfsg-3ubuntu0.2) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up fonts-dejavu-extra (2.37-2build1) ...
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up libgtk-3-common (3.24.33-1ubuntu2.2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Setting up x11-utils (7.7+5build2) ...
Setting up libatk-wrapper-java (0.38.0-5build1) ...
Setting up libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libgdk-pixbuf-2.0-0:amd64 (2.42.8+dfsg-1ubuntu0.4) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.9) ...
Setting up libgtk-3-0:amd64 (3.24.33-1ubuntu2.2) ...
Setting up libgtk-3-bin (3.24.33-1ubuntu2.2) ...
Setting up openjdk-21-jre:amd64 (21.0.10+7-1~22.04) ...
Setting up at-spi2-core (2.44.0-3) ...
Setting up cypher-shell (1:2026.03.1) ...
Setting up neo4j (1:2026.03.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Adding system user `neo4j' (UID 104) ...
Adding new user `neo4j' (UID 104) with group `neo4j' ...
Not creating home directory `/var/lib/neo4j'.
Created symlink /etc/systemd/system/multi-user.target.wants/neo4j.service → /lib/systemd/system/neo4j.service.
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

In [ ]:
#installing neo4j python packages
!pip install neo4j

Collecting neo4j
  Downloading neo4j-6.1.0-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from neo4j) (2025.2)
Downloading neo4j-6.1.0-py3-none-any.whl (325 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 325.3/325.3 kB 6.2 MB/s eta 0:00:00
Installing collected packages: neo4j
Successfully installed neo4j-6.1.0

In [ ]:
! neo4j-admin dbms set-initial-password dakshi

[0.002s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.002s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.004s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.006s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Owner 'neo4j' of '/var/lib/neo4j' and user running this process 'root' differs, potentially resulting in a file permission problem. Ensure that the file has the same owner, or at least has write access for the user running the Neo4j process trying to use it.
A password must be at least 8 characters.
Run with '--verbose' for a more detailed error message.

In [ ]:
#run neo4j
!service neo4j start

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.005s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Directories in use:
home:         /var/lib/neo4j
config:       /etc/neo4j
logs:         /var/log/neo4j
plugins:      /var/lib/neo4j/plugins
import:       /var/lib/neo4j/import
data:         /var/lib/neo4j/data
certificates: /var/lib/neo4j/certificates
licenses:     /var/lib/neo4j/licenses
run:          /var/lib/neo4j/run
Starting Neo4j.
[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Started neo4j (pid:9233). It is available at http://localhost:7474
There may be a short delay until the server is ready.

## Configure Neo4j for GDS

In [ ]:
#adding graph-data-science plugins
#go to plugin directory
%cd /var/lib/neo4j/plugins

/var/lib/neo4j/plugins

In [ ]:
%pwd

'/var/lib/neo4j/plugins'

In [ ]:
#to check its running
! ps -ax | grep neo4j

   9233 ?        Sl     0:30 /usr/lib/jvm/java-21-openjdk-amd64/bin/java -cp /var/lib/neo4j/plugins/*:/etc/neo4j/*:/usr/share/neo4j/lib/* -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:+DisableExplicitGC -Djdk.nio.maxCachedBufferSize=1024 -Dio.netty.tryReflectionSetAccessible=true -Dio.netty.leakDetection.level=DISABLED -Djdk.tls.ephemeralDHKeySize=2048 -Djdk.tls.rejectClientInitiatedRenegotiation=true -XX:FlightRecorderOptions=stackdepth=256 -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --enable-native-access=ALL-UNNAMED -Dorg.neo4j.shaded.lucene9.vectorization.upperJavaFeatureVersion=25 -Dlog4j2.disable.jmx=true -Dlog4j.layout.jsonTemplate.maxStringLength=32768 -Dfile.encoding=UTF-8 org.neo4j.server.Neo4jCommunity --home-dir=/var/lib/neo4j --config-dir=/etc/neo4j
   9384 ?        S      0:00 /bin/bash -c  ps -ax | grep neo4j
   9386 ?        S      0:00 grep neo4j

In [ ]:
#download gds

!wget https://graphdatascience.ninja/neo4j-graph-data-science-2.26.0.jar

--2026-04-06 00:19:43--  https://graphdatascience.ninja/neo4j-graph-data-science-2.26.0.jar
Resolving graphdatascience.ninja (graphdatascience.ninja)... 18.64.174.48, 18.64.174.17, 18.64.174.25, ...
Connecting to graphdatascience.ninja (graphdatascience.ninja)|18.64.174.48|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 66041617 (63M) [application/java-archive]
Saving to: ‘neo4j-graph-data-science-2.26.0.jar’

neo4j-graph-data-sc 100%[===================>]  62.98M  25.7MB/s    in 2.4s

2026-04-06 00:19:46 (25.7 MB/s) - ‘neo4j-graph-data-science-2.26.0.jar’ saved [66041617/66041617]

In [ ]:
#check if the plugin is added

! ls  /var/lib/neo4j/plugins

neo4j-graph-data-science-2.26.0.jar  README.txt

now the graph-data-science is in the neo4j plugins

##install graph data science package

In [ ]:
# 1. need to give perimssion
! cat /etc/neo4j/neo4j.conf | grep dbms.security.procedures.unrestricted

#dbms.security.procedures.unrestricted=my.extensions.example,my.procedures.*

In [ ]:
#add gds

! echo "dbms.security.procedures.unrestricted=gds.*" >> /etc/neo4j/neo4j.conf

In [ ]:
#check the config file is updated or not

! cat /etc/neo4j/neo4j.conf | grep dbms.security.procedures.unrestricted

#dbms.security.procedures.unrestricted=my.extensions.example,my.procedures.*
dbms.security.procedures.unrestricted=gds.*

In [ ]:
#restart neo4j to take affect
!service neo4j stop

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Stopping Neo4j............ stopped.

In [ ]:
!service neo4j start

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Directories in use:
home:         /var/lib/neo4j
config:       /etc/neo4j
logs:         /var/log/neo4j
plugins:      /var/lib/neo4j/plugins
import:       /var/lib/neo4j/import
data:         /var/lib/neo4j/data
certificates: /var/lib/neo4j/certificates
licenses:     /var/lib/neo4j/licenses
run:          /var/lib/neo4j/run
Starting Neo4j.
[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Started neo4j (pid:9571). It is available at http://localhost:7474
There may be a short delay until the server is ready.

## install the graph data science python package

In [ ]:
! pip install graphdatascience

Collecting graphdatascience
  Downloading graphdatascience-1.20-py3-none-any.whl.metadata (7.5 kB)
Collecting multimethod<3.0,>=1.0 (from graphdatascience)
  Downloading multimethod-2.0.2-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: neo4j<7.0,>=4.4.12 in /usr/local/lib/python3.12/dist-packages (from graphdatascience) (6.1.0)
Requirement already satisfied: numpy<2.4 in /usr/local/lib/python3.12/dist-packages (from graphdatascience) (2.0.2)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from graphdatascience) (2.2.2)
Requirement already satisfied: pyarrow<24.0,>=18.0 in /usr/local/lib/python3.12/dist-packages (from graphdatascience) (18.1.0)
Collecting textdistance<5.0,>=4.0 (from graphdatascience)
  Downloading textdistance-4.6.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: tqdm<5.0,>=4.0 in /usr/local/lib/python3.12/dist-packages (from graphdatascience) (4.67.3)
Requirement already satisfied: typing-extensions<5.0,>=4.0 in /usr/local/lib/python3.12/dist-packages (from graphdatascience) (4.15.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from graphdatascience) (2.32.4)
Requirement already satisfied: tenacity>=9.0 in /usr/local/lib/python3.12/dist-packages (from graphdatascience) (9.1.4)
Requirement already satisfied: pydantic>=2.11 in /usr/local/lib/python3.12/dist-packages (from graphdatascience) (2.12.3)
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from neo4j<7.0,>=4.4.12->graphdatascience) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->graphdatascience) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->graphdatascience) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11->graphdatascience) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11->graphdatascience) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11->graphdatascience) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->graphdatascience) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->graphdatascience) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->graphdatascience) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->graphdatascience) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->graphdatascience) (1.17.0)
Downloading graphdatascience-1.20-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 23.6 MB/s eta 0:00:00
Downloading multimethod-2.0.2-py3-none-any.whl (9.6 kB)
Downloading textdistance-4.6.3-py3-none-any.whl (31 kB)
Installing collected packages: textdistance, multimethod, graphdatascience
Successfully installed graphdatascience-1.20 multimethod-2.0.2 textdistance-4.6.3

#Graph Design

#Representation of the data as a property graph model
The deepest reason to use a property graph for this domain is that the interesting queries are multi-hop traversals.  To represent the business model (i.e. Skillify) as a Neo4j property graph:

1.  All the entities will become the nodes of the graph. The user node becomes (:USER) node.  The columns become properties stored directly on each node, so a User node might look like
```
{user_id: "u1", name: "Alice", role: "student"}
```

2. Foreign keys become Relationships (Edges). All the foreign key in the relational schema becomes an actual traversable edge. For ex, a choreographer_id in WorkshopEvent or user making a booking

```
(:User)-[:MADE]->(:Booking)
```

3. Juntion tables becomes the labelled edges with property : The M:M relationship of a user to a workshop , would require a junction table. But in Neo4j ,that table disappears entirely and becomes a single relationship:

```
(:User)-[:REGISTERED_FOR {registered_at: "...", status: "confirmed"}]->(:WorkshopEvent)

```

■ What properties might it make sense to have on edges (relationships between entities) ?

We put a property on an edge when it describes the circumstance of that specific connection not when it describes either of the nodes themselves.

From the Skillify business models , strong candidates are:

[:REGISTERED_FOR] should carry registered_at and status - because the same user can cancel and re register,creating two different edges with different timestamps and statuses.

[:HOSTED_AT] should carry date and start_time - the same studio hosts many different events on different days. The date is a property of this particular pairing of event and studios, not of the studio itself.

[:PAID_BY] should carry paid_at and possibly payment_method - the moment of payment is about this specific settlement of this specific booking.

[:GAVE] (User gives a Review) could carry reviewed_at



■ What should nodes look like?

Nodes in Neo4j are Json objects attached to a label
- (:User) node holds everything intrinsic to that person: {user_id, name, role}
- (:WorkshopEvent) node holds {event_id, title, price, level, dance_style}
- (:Booking) node is an interesting case as relationally booking of often a junction table. In graph table, I will keep it as a real node as it has its own identity (booking_id) and connects to both payment and workshopEvents

#Graph Creation

In [ ]:
from neo4j import GraphDatabase

In [ ]:
!neo4j-admin dbms set-initial-password neo4_pass

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Changed password for user 'neo4j'. IMPORTANT: this change will only take effect if performed before the database is started for the first time.

In [ ]:
!service neo4j restart
import time
time.sleep(15)

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Stopping Neo4j............ stopped.
[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Directories in use:
home:         /var/lib/neo4j
config:       /etc/neo4j
logs:         /var/log/neo4j
plugins:      /var/lib/neo4j/plugins
import:       /var/lib/neo4j/import
data:         /var/lib/neo4j/data
certificates: /var/lib/neo4j/certificates
licenses:     /var/lib/neo4j/licenses
run:          /var/lib/neo4j/run
Starting Neo4j.
[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Started neo4j (pid:10043). It is available at http://localhost:7474
There may be a short delay until the server is ready.

In [ ]:
from neo4j import GraphDatabase

uri = "bolt://localhost:7687"
username = "neo4j"
password = "neo4_pass"

driver = GraphDatabase.driver(uri, auth=(username, password))
driver.verify_connectivity()

In [ ]:
def run_query(tx, query):
        result = tx.run(query)
        return result.data()


with driver.session() as session:
  query= "SHOW DATABASES yield name;"
  result = session.execute_read(run_query, query)
  print(result)

[{'name': 'neo4j'}, {'name': 'system'}]

In [ ]:
with driver.session() as session:
  session.run("CREATE (:User {user_id: 'u1', name: 'Alice Chen', role: 'student'})")
  session.run("CREATE (:User {user_id: 'u2', name: 'Marcus webb', role: 'student'})")
  session.run("CREATE (:User {user_id: 'u3', name: 'Bob', role: 'student'})")
  session.run("CREATE (:ChoreographerProfile {choreographer_id: 'cp1', name: 'Sofia Reyes', rating: 4.8})")
  session.run("CREATE (:ChoreographerProfile {choreographer_id: 'cp2', name: 'James Rees', rating: 3.2})")
  session.run("CREATE (:Studio {studio_id: 's1', name: 'Rhythm Space', capacity: 30})")
  session.run("CREATE (:WorkshopEvent {event_id: 'e1', title: 'Afrobeats Fundamentals', price: 25.0})")
  session.run("CREATE (:Booking {booking_id: 'b1', status: 'confirmed'})")
  session.run("CREATE (:Booking {booking_id: 'b2', status: 'initated'})")
  session.run("CREATE (:Payment {payment_id: 'p1', amount: 25.0, payment_status: 'completed'})")
  session.run("CREATE (:Review {review_id: 'r1', rating: 5, comment: 'Amazing class!'})")
  print("Nodes created.")

Nodes created.

In [ ]:
with driver.session() as session:
    session.run("""
        MATCH (u:User {user_id: 'u1'}), (b:Booking {booking_id: 'b1'})
        CREATE (u)-[:MADE {booked_at: '2024-11-01'}]->(b)
    """)
    session.run("""
        MATCH (b:Booking {booking_id: 'b1'}), (e:WorkshopEvent {event_id: 'e1'})
        CREATE (b)-[:FOR_EVENT]->(e)
    """)
    session.run("""
        MATCH (b:Booking {booking_id: 'b1'}), (p:Payment {payment_id: 'p1'})
        CREATE (b)-[:PAID_BY {paid_at: '2024-12-01'}]->(p)
    """)
    session.run("""
        MATCH (cp:ChoreographerProfile {choreographer_id: 'cp1'}), (e:WorkshopEvent {event_id: 'e1'})
        CREATE (cp)-[:CONDUCTS]->(e)
    """)
    session.run("""
        MATCH (e:WorkshopEvent {event_id: 'e1'}),(s:Studio {studio_id: 's1'})
        CREATE (e)-[:HOSTED_AT {date: '2024-11-15', start_time: '10:00'}]->(s)
    """)
    print("Relationships Created")

Relationships Created

In [ ]:
#verify

with driver.session() as session:
  result = session.run("MATCH (n) RETURN labels(n)[0] AS label, count(n) AS count")
  for row in result:
    print(row["label"], "→", row["count"])

User → 3
ChoreographerProfile → 2
Studio → 1
WorkshopEvent → 1
Booking → 2
Payment → 1
Review → 1

#Graph Query

**What question do you want to answer and why does it matter to your
business?**

The business question I want to ask is *Which choreogrpahers are generting the most booking revenue and through which workshops?*

This matters because it tells who the top performers are, which styles are selling and where to invest.

In [ ]:
with driver.session() as session :
  result = session.run("""
      MATCH (cp:ChoreographerProfile)-[:CONDUCTS]->(e:WorkshopEvent)
              <-[:FOR_EVENT]-(b:Booking)
              -[:PAID_BY]->(p:Payment)

      WHERE p.payment_status = 'completed'
      RETURN cp.name AS choreographer,
             e.title AS workshop,
             count(b) AS total_bookings,
             sum(p.amount) AS total_revenue
     ORDER BY total_revenue DESC
    """)

  for row in result:
    print(f"{row['choreographer']} | {row['workshop']} |"
              f"bookings: {row['total_bookings']} | "
              f"revenue: £{row['total_revenue']:.2f}")

Sofia Reyes | Afrobeats Fundamentals |bookings: 1 | revenue: £25.00

This query is a graph query as it traverses through 4 nodes and follows a natural connection between them. In relational database this query would require three JOINS across four tables.

The path reads a sentence "a choreographer conducts an event, which has bookings, which have payments."

#Graph Analysis (Analytical)

In [ ]:
#Loading LastFM dataset from Graph Data Science (GDS),
from graphdatascience import GraphDataScience

uri = "bolt://localhost:7687"
username = "neo4j"
password = "neo4_pass"

gds = GraphDataScience(uri, auth=(username, password))

print(gds.version())

2.26.0

In [ ]:
lastfm = gds.graph.load_lastfm()

In [ ]:
print("Graph name :" , lastfm.name())
print("Node count :" , lastfm.node_count())
print("Node labels :" , lastfm.node_labels())
print("Relationship count :" , lastfm.relationship_count())
print("Relationship types :" , lastfm.relationship_types())

Graph name : lastfm
Node count : 19914
Node labels : ['Artist', 'User']
Relationship count : 584060
Relationship types : ['TAGGED', 'IS_FRIEND', 'LISTEN_TO']

##Centrality

Degree centrality tells the count of how many direct connections (edges) a node has.

**What does degree centrality tell you about this node?**

For the artist node  in LastFM, a high degree means many users have listened to that artist — making it the most popular one in the dataset.

#EXTRA CREDT

In [ ]:
#run degree centrality on the graph

results = gds.degree.stream(lastfm, orientation = "UNDIRECTED")

#sort and get the top node
top_node = results.sort_values("score", ascending=False).head(1)


print("Most popular node ID:", top_node["nodeId"].values[0])
print("Degree centrality score:", top_node["score"].values[0])

Most popular node ID: 1672
Degree centrality score: 5320.0

In [ ]:
#Print the most popular node

print("Most popular node: ", results.iloc[0])
# print("Degree centrality score:", results.iloc[0]["score"])

Most popular node:  nodeId      2.0
score     216.0
Name: 0, dtype: float64

#Machine Learning Task

● Choose a supervised ML task (ex. classification) you would like to perform against the LastFM dataset using the GDS library.

I am doing a supervisedd Link Prediction task , similar to recommendation engine for the LastFM dataset . The goal is to predict whether two disconnected users should be friends

● Create a model

To create a model , I will create a neo4j logistic pipeline .

● Train the model (using a training data)

● Make predictions (using test data)

In [ ]:
#printing the relations
rel_types = gds.run_cypher("MATCH ()-[r]->() RETURN DISTINCT type(r) AS Relationship_Type")
display(rel_types)

  Relationship_Type
0              MADE
1         FOR_EVENT
2           PAID_BY
3          CONDUCTS
4         HOSTED_AT

In [ ]:
#relations and nodes in the lastfm data
print(f"Graph Name: {lastfm.name()}")
print(f"Relationship Count: {lastfm.relationship_count():,}")
print(f"Node Count: {lastfm.node_count():,}")

Graph Name: lastfm
Relationship Count: 584,060
Node Count: 19,914

In [ ]:
schema_info = gds.run_cypher("CALL gds.graph.list('lastfm') YIELD schema RETURN schema")

In [ ]:
# schema_info
# Print it out nicely
import json
print(json.dumps(schema_info['schema'][0], indent=2))

{
  "graphProperties": {},
  "relationships": {
    "TAGGED": {
      "month": "Float (DefaultValue(NaN), TRANSIENT, Aggregation.NONE)",
      "tagID": "Float (DefaultValue(NaN), TRANSIENT, Aggregation.NONE)",
      "year": "Float (DefaultValue(NaN), TRANSIENT, Aggregation.NONE)",
      "day": "Float (DefaultValue(NaN), TRANSIENT, Aggregation.NONE)",
      "timestamp": "Float (DefaultValue(NaN), TRANSIENT, Aggregation.NONE)"
    },
    "IS_FRIEND": {},
    "LISTEN_TO": {
      "weight": "Float (DefaultValue(NaN), TRANSIENT, Aggregation.NONE)"
    }
  },
  "nodes": {
    "Artist": {
      "rawId": "Integer (DefaultValue(-9223372036854775808), PERSISTENT)"
    },
    "User": {
      "rawId": "Integer (DefaultValue(-9223372036854775808), PERSISTENT)"
    }
  }
}

In [ ]:
#clear all the existing pipelines to create new

gds.run_cypher("CALL gds.beta.pipeline.drop('lp_pipeline', false)")

Empty DataFrame
Columns: [pipelineInfo, pipelineName, pipelineType, creationTime]
Index: []

In [ ]:
#create a new link prediction pipeline

gds.run_cypher("CALL gds.beta.pipeline.linkPrediction.create('lp_pipeline')")

,name,nodePropertySteps,featureSteps,splitConfig,autoTuningConfig,parameterSpace
0,lp_pipeline,[],[],"{'negativeSamplingRatio': 1.0, 'trainFraction'...",{'maxTrials': 10},"{'MultilayerPerceptron': [], 'LogisticRegressi..."

In [ ]:
#Turn a user's network position into a 128-number vector using FASTRP

gds.run_cypher("""CALL gds.beta.pipeline.linkPrediction.addNodeProperty('lp_pipeline', 'fastRP',
                  { mutateProperty: 'embedding',
                    embeddingDimension: 128,
                    randomSeed: 42
                    })
               """)

,name,nodePropertySteps,featureSteps,splitConfig,autoTuningConfig,parameterSpace
0,lp_pipeline,"[{'name': 'gds.fastRP.mutate', 'config': {'ran...",[],"{'negativeSamplingRatio': 1.0, 'trainFraction'...",{'maxTrials': 10},"{'MultilayerPerceptron': [], 'LogisticRegressi..."

In [ ]:
#combine vectors (multiplies User A's vector with User B's vector)

gds.run_cypher("""
CALL gds.beta.pipeline.linkPrediction.addFeature('lp_pipeline', 'hadamard',
                  { featureName: 'dotProduct',
                    nodeProperties: ['embedding']
                    })
               """)

print("pipeline built successfully")

pipeline built successfully

##Preprocessing Data

In [ ]:
#1. Train/test split
gds.run_cypher(""" CALL gds.beta.pipeline.linkPrediction.configureSplit('lp_pipeline', {
                    testFraction:0.2,
                    trainFraction:0.8,
                    validationFOlds: 5
                    })
                    """)

,name,nodePropertySteps,featureSteps,splitConfig,autoTuningConfig,parameterSpace
0,lp_pipeline,"[{'name': 'gds.fastRP.mutate', 'config': {'ran...","[{'name': 'HADAMARD', 'config': {'nodeProperti...","{'negativeSamplingRatio': 1.0, 'trainFraction'...",{'maxTrials': 10},"{'MultilayerPerceptron': [], 'LogisticRegressi..."

In [ ]:
#add logistic regression

gds.run_cypher(""" CALL gds.beta.pipeline.linkPrediction.addLogisticRegression('lp_pipeline',
                {
                 maxEpochs:100,
                  penalty:0.01
                })
                """)

,name,nodePropertySteps,featureSteps,splitConfig,autoTuningConfig,parameterSpace
0,lp_pipeline,"[{'name': 'gds.fastRP.mutate', 'config': {'ran...","[{'name': 'HADAMARD', 'config': {'nodeProperti...","{'negativeSamplingRatio': 1.0, 'trainFraction'...",{'maxTrials': 10},"{'MultilayerPerceptron': [], 'LogisticRegressi..."

In [ ]:
#clear any existing models

gds.run_cypher("CALL gds.beta.model.drop('lastfm_lp_model', false)")

Empty DataFrame
Columns: [modelInfo, trainConfig, graphSchema, loaded, stored, creationTime, shared]
Index: []

##Training Model

In [ ]:
# 4. Train the model and get the evaluation metrics

train_results = gds.run_cypher("""CALL gds.beta.pipeline.linkPrediction.train('lastfm',
                                {
                                  pipeline: 'lp_pipeline',
                                  modelName: 'lastfm_lp_model',
                                  targetRelationshipType: 'IS_FRIEND',
                                  randomSeed: 42
                                })
                                YIELD modelInfo
                                RETURN
                                  modelInfo.bestParameters AS best_parameters,
                                  modelInfo.modelName AS model,
                                  modelInfo.metrics.AUCPR.outerTrain AS train_aucpr,
                                  modelInfo.metrics.AUCPR.test AS test_aucpr,
                                  modelInfo.train.roc
                                """)

print("-----Training Results-----")
display(train_results)

-----Training Results-----

,best_parameters,model,train_aucpr,test_aucpr,modelInfo.train.roc
0,"{'maxEpochs': 100, 'minEpochs': 1, 'classWeigh...",lastfm_lp_model,0.856924,0.850684,None

##Predictions

We will look at users who are not currently connected and predict most likely top 10 new predictions

In [ ]:
# Make predictions
predictions = gds.run_cypher("""
CALL gds.beta.pipeline.linkPrediction.predict.stream('lastfm', {
  modelName: 'lastfm_lp_model',
  topN: 10,
  threshold: 0.5
})
YIELD node1, node2, probability
RETURN
  gds.util.nodeProperty('lastfm', node1, 'rawId') AS user1_id,
  gds.util.nodeProperty('lastfm', node2, 'rawId') AS user2_id,
  probability

ORDER BY probability DESC
""")

print("--- Top 10 Predicted New Friendships ---")
display(predictions)

--- Top 10 Predicted New Friendships ---

   user1_id  user2_id  probability
0     435.0    1759.0     0.501340
1     603.0     776.0     0.501320
2    1356.0    1453.0     0.501312
3     259.0     277.0     0.501305
4     218.0     575.0     0.501304
5     776.0    1759.0     0.501296
6     603.0    1759.0     0.501296
7     206.0    1677.0     0.501280
8      99.0     218.0     0.501276
9     218.0     306.0     0.501275

## How did you do?

1. FASTRP algorythm : to generate the node embeddings, which translated each users positions in the social network as a vector - Users with similar friend circles received similar vectors.

2. Hadamard Product : Combine pairs of user vectors into single vector

3. Test train split into 80/20 and logistic regression classifier was used to predict the probability of the relation "IS_FRIEND" link existing based on those combined features

4. The model successfully trained and was evaluated using the AUCPR (Area Under the Precision-Recall Curve) metric.

Because social networks heavily rely on triadic closure (friends of friends become friends), the structural FastRP embeddings captured these graph patterns well, allowing the model to accurately predict the top 10 new likely connections.

#EXTRA CREDIT - Graph Algorythm

Using the PAGERANK algorythm to find most influencial users based on friendships

In [ ]:
pagerank_results = gds.run_cypher(""" CALL gds.pageRank.stream('lastfm', {
                    relationshipTypes: ['IS_FRIEND']
                    })
                    YIELD nodeId, score
                    RETURN
                     gds.util.nodeProperty('lastfm', nodeId, 'rawId') AS user_id,
                     score AS pagerank_score
                    ORDER BY pagerank_score DESC
                    LIMIT 10

                    """)
print("------TOP 10 MOST INFLUENCIAL USERS-------")
display(pagerank_results)

------TOP 10 MOST INFLUENCIAL USERS-------

   user_id  pagerank_score
0     78.0        9.611143
1   1543.0        9.544590
2   1281.0        8.610313
3   1258.0        7.712240
4   1210.0        7.059164
5    831.0        6.840102
6    298.0        5.561350
7   1488.0        5.353474
8   1213.0        5.171447
9   1597.0        5.069267

● Explain in words what you were trying to do / what your algorithm did.

I wanted to identify the most 'influential' or central users within the LastFM social network. Instead of simply counting which user has the highest raw number of friends (which is basic Degree Centrality). I wanted to find users who are deeply embedded in the network and connected to other highly connected users

I used the PageRank algorithm, which measures the transitive influence of nodes in a graph. It operates on the principle that connections are not created equal and a friendship with a highly influential user contributes more to your own influence score than a friendship with an isolated user.


Mathematicallly, it is a random surfer traversing through the network

The final pagerank score represents the probability that this random surfer will eventually land on that specific user.

The code streamed the graph data, ran this calculation across the IS_FRIEND relationships, and returned the top 10 users sorted by their PageRank score, revealing the core influencers of the LastFM community.

#EXTRA CREDIT - GRAPH RAG

## Why I Chose the Topic and How It Relates to Graph Databases.

GraphRAG is the most exciting evolutions right now as traditional RAG systems rely on vector databases, which store textt chunks as flat isolated data points just based on semantice similarity.

GraphRAG shifts this foundation by using graph dataabses like neo4j to map out the data. GraphRAG uses the interconnected structure of graph databases to feed LLMs a map of relationships rather than just pile of text.

## Pretend You Are Teaching Someone About It

It works by first creating a map by extracting the entities and the relationships . And when the user asks a question, instead of searching for the documents, it literally traces the connected lines.

Take a real world use case for Financial Fraud Detection.Fraudsters often hide illicit money movements through layers of shell companies and micro-transactions.

Standard Graph, might pull documents about one suspicious company, but it misses the bigger picture.

On the other side, GraphRAG can traverse through the network - "COMPANY A TRANSFEERED TO COMPANY B, WHICH SHARES A DIRECTOR WITH COMPANY C AND WHICH WAS PREVIOUSLY FLAGGED FOR MONEY LAUNDERING " . This allow the AI to accurately explain the multi-hop money laundering scheme.

## Are There Any Tradeoffs or Pitfalls to Watch Out For?

Yes, Graph RAG is powerful, but it comes with several distinct challenges:
1. High Indexing Costs
2. Difficulty with dynamic Updates
3. Extraction Hallucinations
4. Overkill for Simple Queries

##Did You Learn Anything Particularly Interesting or Surprising?

One surprising fact is that Graph RAG despite adding layers , can actually lower the token costs and reduce hallucinations at query time. This is because the standardRAG lacks relationship awareness, it often has to stuff the LLM's context window with more context. GraphRAG on the other hand only lets in the exact entities and explicit relationships relevant to the prompt.

#